name: Order Service

on:
  push:
    paths:
      - order-service/**
    branches:
      - '**'
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      working-directory: ./order-service
    defaults:
      run:
        working-directory: ${{ env.working-directory }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Make Maven wrapper executable
        run: chmod +x mvnw

      - name: Force update Maven dependencies and build
        run: ./mvnw clean install -U

      - name: Run tests
        run: ./mvnw test